name: Post release triggers

on: 
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF##*/})"
        id: tag_name

      - name: Update Homebrew recipe
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: xxxserxxx/homebrew-gotop
          event-type: my-release
          client-payload: '{"tag": "${{ steps.tag_name.outputs.tag }}"}'

      - name: Update and inform Homebrew
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.homebrew }}
          formula: gotop
          tag: ${{ steps.tag_name.outputs.tag }}

      - name: Update Arch AURs
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: xxxserxxx/gotop-linux
          event-type: my-release
          client-payload: '{"tag": "${{ steps.tag_name.outputs.tag }}"}'
